
version: '3'
services:
  # MongoDB Service
  mongodb:
    image: mongo:4.0.8
    container_name: ${MONGO_CONTAINER_NAME}  # Container name based on environment variable
    restart: unless-stopped
    command: mongod --auth  # Run MongoDB with authentication
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}  # MongoDB root username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}  # MongoDB root password
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}  # Initial MongoDB database
    ports:
      - ${MONGO_DOCKER_PORT}:${MONGO_HOST_PORT}  # Map container port to host port
    volumes:
      - mongodbdata:/data/db  # Mount volume for MongoDB data persistence
    networks:
      - backend  # Connect to the backend network

  # Python Cron Service
  python_cron:
    build:
      context: ./ 
      dockerfile: python_cron/Dockerfile 
    container_name: python-cron
    restart: unless-stopped
    stdin_open: true  # Enable interactive mode (docker run -i)
    tty: true         # Allocate a pseudo-TTY (docker run -t)
    environment:
      - TZ=UTC  # Set container timezone to UTC
    ports:
      - "6000:6000"  # Map container port to host port
    networks:
      - backend  # Connect to the backend network
    depends_on:
      - mongodb  # Depend on the MongoDB service, start after it
    volumes:
      - cronlog:/var/log/cron  # Mount volume for cron logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend:
    driver: bridge  # Define a custom network named 'backend' with the bridge driver

volumes:
  mongodbdata:
    driver: local  # Define a local volume named 'mongodbdata'
  cronlog:
    driver: local  # Define a local volume named 'cronlog'
