FROM alpine:3.18

LABEL MAINTAINER="Etienne Vaneecloo <etienne.vaneecloo@student-cs.fr>"

RUN apk --update add nginx && \
  ln -sf /dev/stdout /var/log/nginx/access.log && \
  ln -sf /dev/stderr /var/log/nginx/error.log && \
  mkdir /etc/nginx/sites-enabled/ && \
  mkdir -p /run/nginx && \
  rm -rf /etc/nginx/conf.d/default.conf && \
  rm -rf /var/cache/apk/* \
  rm -r /etc/nginx/nginx.conf

COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
# CMD ["nginx"]
